title: SUCIALISM
theme: jekyll-theme-minimal
logo: /assets/img/avatar.jpg
description: Hello, my name is John Su. Welcome to my homepage. I'm a senior technical director, technical artist, game engineer, VFX artist, and art-lover. 